# Generated by Django 3.1.2 on 2020-10-28 22:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0002_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='temporary'),
            preserve_default=False,
        ),
    ]
