# Generated by Django 3.1.2 on 2020-10-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0003_question_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='data',
            field=models.CharField(max_length=200),
        ),
    ]
